### PR TITLE
Haskell colours

### PR DESCRIPTION
**Pull request by chris-bacon**
Hello, 

I've added support for Haskell with this PR.

haskell example

### CODE REVIEW

**Comment by chris-bacon** [comment]
@rakr

**Comment by rakr** [comment]
Thanks for this and sorry for the late merge

**Comment by chris-bacon** [comment]
Cheers @rakr! Just making sure, but you seem to have closed the PR instead of merging 😀

**Comment by rakr** [comment]
Silly me.
Thanks again for the PR

**Comment by chris-bacon** [comment]
Haha, no problem! Thanks 😀

**Pull request merged**
