### PR TITLE
Add VertSplit border; Clear Folded background

### PR DESCRIPTION
**Pull request by ashfinal**

### CODE REVIEW

**Comment by rakr** [comment]
Hi, thanks for submitting this PR, and sorry for the delay, I took a month off (completely disconnecting from the Internet).

I am not sure if I would merge the PR as it is really a matter of taste, I wanted the splits to be as subtle as possible hence just the use of the foreground attribute.

One has now a "public API" that allow user to tweak the colorscheme to their taste/needs, I would suggest you give it a try.

This PR makes me think that an 'alternate' version can be developed, people would toggle a variable and depending on the value would apply specific settings.

These variables/values would be along the lines of "one-subtle", "one-bold", ...

If my suggestion above does not fly, do you mind opening an issue for this?

**Comment by ashfinal** [comment]
Thanks for your reply. I've create an issue to explain why this PR is necessary.

**Comment by Dbz** [comment]
@ashfinal would you be able to post how to do this using the public API? I'd also like to change these attributes, but I am very new to vim. Thank you for any help you can provide!

**Comment by ashfinal** [comment]
@Dbz Sorry for the late reply. 

As [here](https://github.com/rakr/vim-one#customising-one-without-fork) instructs:
`call one#highlight('vimLineComment', 'cccccc', '', 'none')`
All you need to do is add some lines like this in your vimrc file. but I guess your problem may lay which "color group" I should highlight? Where does the `vimLineComment` come from? 

Well, this script will help you out. Copy [this paragraph](https://github.com/ashfinal/vimrc-config/blob/d5a31aa090faf465678e093cba4f1fc222610d83/.vimrc#L383) into your vimrc, and restart Vim.
Then you can know the group and color under your cursor.

**Comment by wsdjeg** [comment]
why remove fold background？ It will be hard for user to find the  fold.

**Pull request merged**
